version: '3.8'

services:
  node0:
    hostname: node0
    image: docker.io/strongly-web3/jam
    command: ["./jam", "--port=9000", "--validatorindex=0"]
    networks:
      - jam-testnet

  node1:
    hostname: node1
    image: docker.io/strongly-web3/jam
    command: ["./jam", "--port=9000", "--validatorindex=1"]
    networks:
      - jam-testnet

  node2:
    hostname: node2
    image: docker.io/strongly-web3/jam
    command: ["./jam", "--port=9000", "--validatorindex=2"]
    networks:
      - jam-testnet

  node3:
    hostname: node3
    image: docker.io/strongly-web3/jam
    command: ["./jam", "--port=9000", "--validatorindex=3"]
    networks:
      - jam-testnet

  node4:
    hostname: node4
    image: docker.io/strongly-web3/jam
    command: ["./jam", "--port=9000", "--validatorindex=4"]
    networks:
      - jam-testnet

  node5:
    hostname: node5
    image: docker.io/strongly-web3/jam  
    command: ["./jam", "--port=9000", "--validatorindex=5"]
    networks:
      - jam-testnet

networks:
  jam-testnet:
    driver: bridge
