[jamchain]
default_args = ["--ts ${TIMESTAMP} --validatorindex=${VALIDATORINDEX} --genesis=genesis.json --datadir /tmp/node${VALIDATORINDEX}"]
chain = "tiny"
V = 6
C = 2
E = 12
P = 6
Y = 8

  [[validator]]
  name = "Alice"
  command = "bin/jam-duna/jam --port=9900"

  [[validator]]
  name = "Bob"
  command = "bin/jam-duna/jam --port=9901"

  [[validator]]
  name = "Charlie"
  command = "bin/jam-duna/jam --port=9902"

  [[validator]]
  name = "Dave"
  command = "bin/jam-duna/jam --port=9903"

  [[validator]]
  name = "Eve"
  command = "bin/jam-duna/jam --port=9904"

  [[validator]]
  name = "Fergie"
  command = "bin/jam-duna/jam --port=9905"
